### ISSUE TITLE
Controlboard plugin correctly manages multiple controlboards for the same robot

### ISSUE THREAD

**Issue by xela-95** [robotology/gz-sim-yarp-plugins#107] opened 2024-03-05 11:54 UTC

**Comment by xela-95** [comment] 2024-03-05 12:08
Duplicate of #89 .
@traversaro could you delete this please?

**Comment by traversaro** [comment] 2024-03-05 13:03
No need to delete, we can just close it as duplicate of https://github.com/robotology/gz-sim-yarp-plugins/issues/89 .

**Closed by traversaro** 2024-03-05 13:03 UTC
Labels: phase:implementation
